Show course map
CodeSoom/project-react-2-hyejineee pull request #20
Opened 2020-11-25 15:50 UTC by hyejineee

네이버 지도 api와 산림청 데이터를 사용하여 등산로 지도를 볼 수 있도록 합니다. 

- [ ] e2e테스트 작성 
- [ ] 네이버 지도 API 설정 
- [ ] 등산로 좌표 데이터 넣기 
- [ ] 구현 
- [ ] 리팩터링

2020-12-01 16:59 UTC, Kihyun92 commented
이 PR은 어떻게 진행되고 있나요~?

2020-12-02 06:37 UTC, hyejineee commented
> 이 PR은 어떻게 진행되고 있나요~?

오늘부터 열심히...
![85715f720bb1da77ac5ce72b9454b4df](https://user-images.githubusercontent.com/44992033/100837207-1ec64500-34b4-11eb-9994-b218dcad3d44.jpg)

2020-12-05 14:15 UTC, Kihyun92 commented
나머지 작업들은 잘 진행되고 있는지 궁금합니다~~ 😁

2020-12-05 14:42 UTC, hyejineee commented
> 나머지 작업들은 잘 진행되고 있는지 궁금합니다~~ 😁

드디어 지도에 등산코스를 그렸습니다...
![스크린샷 2020-12-05 오후 11 32 05](https://user-images.githubusercontent.com/44992033/101245742-44707a00-3752-11eb-95af-d6c496e92f5d.png)

![HHhl4uR](https://user-images.githubusercontent.com/44992033/101245920-6dddd580-3753-11eb-82fe-20e018143680.gif)

2020-12-06 03:45 UTC, hyejineee commented
> 네이버 지도 api와 산림청 데이터를 사용하여 등산로 지도를 볼 수 있도록 합니다.
> 
> * [x]  e2e테스트 작성
> * [x]  네이버 지도 API 설정
> * [x]  등산로 좌표 데이터 넣기
> * [x]  구현
> * [ ]  리팩터링

2020-12-06 15:44 UTC, Kihyun92 requested changes
👍

2020-12-06 15:44 UTC, Kihyun92 commented on src/container/CourseMapContainer.jsx
> +  const [courseGPX, setGPXFile] = useState();
초기 값을 넘겨주는게 좋을 것 같아요~

2020-12-06 15:44 UTC, Kihyun92 commented on src/presentational/CourseMap.jsx
> +  });
두번째 인자로 빈 배열을 넘겨주는게 좋을 것 같아요~

2020-12-07 08:21 UTC, hyejineee commented on src/presentational/CourseMap.jsx
> +  });
이 부분은 이번 주 함수형 자바스크립트 공부 후에 모나드 사용해서 리팩토링해 볼 예정입니다!

2020-12-07 08:21 UTC, merged